Repository kserve/modelmesh, pull requests merged in 2022-08, with the labels that each got.

#48 Adding ckadner as a reviewer
  OWNERS
Labels: approved, lgtm, do-not-merge/invalid-owners-file

#50 docs: Indicate which model-runtime proto SPI rpcs are optional
  src/main/proto/current/model-runtime.proto
Labels: documentation, approved, lgtm

#49 feat: Rework second-copy scaling logic
  src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
  src/test/java/com/ibm/watson/modelmesh/ModelMeshEvictionsTest.java
Labels: approved, lgtm

#53 deps: Refresh dependencies
  pom.xml
Labels: approved, lgtm

#54 fix: Adjustments/cleanup missed from prior PR #49
  src/main/java/com/ibm/watson/modelmesh/ModelMesh.java
Labels: approved, lgtm

#55 deps: Update grpc and netty dependencies
  pom.xml
Labels: approved
