Repository kserve/modelmesh, pull requests merged in 2023-05, with the labels that each got.

#93 chore: update dependencies to address vulnerabilities
  pom.xml
Labels: approved, lgtm

#92 Fix multi-platform build
  .dockerignore
  .github/workflows/build.yml
  Dockerfile
  README.md
Labels: approved

#96 Let RemotePayloadProcessor send also gRPC call Metadata
  src/main/java/com/ibm/watson/modelmesh/payload/RemotePayloadProcessor.java
  src/test/java/com/ibm/watson/modelmesh/SidecarModelMeshPayloadProcessingTest.java
  src/test/java/com/ibm/watson/modelmesh/payload/RemotePayloadProcessorTest.java
Labels: enhancement, approved, lgtm
