Repository kserve/modelmesh, pull requests merged in 2023-10, with the labels that each got.

#85 docs: Add developer instructions to README.md
  CONTRIBUTING.md
  README.md
  developer-guide.md
Labels: documentation, approved, lgtm

#110 docs: Add ModelMesh documentation
  README.md
  docs/README.md
  docs/configuration/README.md
  docs/configuration/payloads.md
  docs/configuration/scaling.md
  docs/configuration/tls.md
  docs/images/vmodels.png
  docs/metrics.md
  docs/vmodels.md
  src/main/java/com/ibm/watson/modelmesh/payload/README.md
Labels: documentation, approved, lgtm

#114 Bump netty - CVE-2023-44487
  pom.xml
Labels: approved, lgtm

#115 deps: Update various dependencies
  pom.xml
  src/test/java/com/ibm/watson/modelmesh/AbstractModelMeshTest.java
  src/test/java/com/ibm/watson/modelmesh/LegacyAddRemoveProtoTest.java
  src/test/java/com/ibm/watson/modelmesh/LegacyTasProtoTest.java
  src/test/java/com/ibm/watson/modelmesh/ModelMeshHeaderLoggingTest.java
  src/test/java/com/ibm/watson/modelmesh/VModelsTest.java
  src/test/java/com/ibm/watson/modelmesh/example/ExampleModelClient.java
Labels: approved

#116 chore: Configure CodeQL
  .github/workflows/codeql.yml
Labels: approved, lgtm
